# Generated by Django 6.0 on 2025-12-16 17:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='Всего оценок')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('five_star_count', models.IntegerField(default=0, verbose_name='5 звезд')),
                ('four_star_count', models.IntegerField(default=0, verbose_name='4 звезды')),
                ('three_star_count', models.IntegerField(default=0, verbose_name='3 звезды')),
                ('two_star_count', models.IntegerField(default=0, verbose_name='2 звезды')),
                ('one_star_count', models.IntegerField(default=0, verbose_name='1 звезда')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('trainer', models.OneToOneField(limit_choices_to={'role': 'TR'}, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Статистика тренера',
                'verbose_name_plural': 'Статистика тренеров',
            },
        ),
        migrations.CreateModel(
            name='TrainerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка тренера',
                'verbose_name_plural': 'Оценки тренеров',
                'ordering': ['-created_at'],
                'unique_together': {('trainer', 'user')},
            },
        ),
    ]
